# Classification using Support  Vector Machine

# Load dataset

In [2]:
data_name="pima"

In [3]:
from scipy.io import loadmat
path="./ML/dataset/"

if data_name=="pima":
    data = loadmat(path+'pima_dataset.mat')
elif data_name=="heart":
    data = loadmat(path+'heart_dataset.mat')
elif data_name=="hepatitis":
    data = loadmat(path+'heart_dataset.mat')
elif data_name=="ECG":
    data = loadmat(path+'ECG_dataset.mat')
elif data_name=="dermatology":
    data = loadmat(path+'dermatology_dataset.mat')
elif data_name=="kidney":
    data = loadmat(path+'kidney_dataset.mat')
elif data_name=="liver":
    data = loadmat(path+'liver_dataset.mat')
elif data_name=="lung":
    data = loadmat(path+'lung_dataset.mat')
elif data_name=="parkinsons":
    data = loadmat(path+'parkinsons_dataset.mat')
elif data_name=="SPECT":
    data = loadmat(path+'SPECT_dataset.mat')    
elif data_name=="SPECTF":
    data = loadmat(path+'SPECTF_dataset.mat')
elif data_name=="thyroid":
    data = loadmat(path+'thyroid_dataset.mat') 
elif data_name=="vertebral":
    data = loadmat(path+'vertebral_dataset.mat') 
elif data_name=="wdbc":
    data = loadmat(path+'wdbc_dataset.mat')
elif data_name=="wpbc":
    data = loadmat(path+'wpbc_dataset.mat')
    
X=data['norm_data']
y=data['target']
X.shape

(768, 8)

In [35]:
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
import xlwt
import timeit

In [36]:
from sklearn.neural_network import MLPClassifier
from sklearn import svm

In [37]:
from sklearn.metrics import *

# Classification performance measure function

In [38]:
def myConfusion_Matrix(y_true, y_pred):
    conf_matrix=np.array([[0,0],[0,0]])
    for i in range(0,y_true.shape[0]):
        if y_true[i]==1 and y_pred[i]==1:
            conf_matrix[0][0]+=1
        if y_true[i]==0 and y_pred[i]==1:
            conf_matrix[0][1]+=1
        if y_true[i]==1 and y_pred[i]==0:
            conf_matrix[1][0]+=1
        if y_true[i]==0 and y_pred[i]==0:
            conf_matrix[1][1]+=1
    return conf_matrix          

In [39]:
def classification_performance(conf_matrix):
    accureacy=(conf_matrix[0][0]+conf_matrix[1][1])/(conf_matrix[0][0]+conf_matrix[0][1]+conf_matrix[1][0]+conf_matrix[1][1])
    recall=(conf_matrix[0][0])/(conf_matrix[0][0]+conf_matrix[1][0])
    specificity=(conf_matrix[1][1])/(conf_matrix[0][1]+conf_matrix[1][1])
    precision=(conf_matrix[0][0])/(conf_matrix[0][0]+conf_matrix[0][1])
    F1_score=(2*precision*recall)/(precision+recall)
    GM=math.sqrt(recall*specificity)
    FPR=1-specificity
    return accureacy,recall,specificity,precision,F1_score,GM,FPR

In [56]:
def training_accuracy(y_train, y_train_pred):
    train_accuracy=0;
    for i in range(0,y_train.shape[0]):
        if y_train[i] == y_train_pred[i]:
            train_accuracy+=1
    return  train_accuracy/y_train.shape[0]      

In [61]:
#excel file writing
workbook = xlwt.Workbook()  
filename="svm.xls"    
sheet = workbook.add_sheet(data_name) 
sheet.write(0, 0, 'Accuracy') 
sheet.write(0, 1, 'recall') 
sheet.write(0, 2, 'specificity') 
sheet.write(0, 3, 'precision') 
sheet.write(0, 4, 'F1_score')
sheet.write(0, 5, 'GM')
sheet.write(0, 6, 'FPR')
sheet.write(0, 7, 'Training Accuracy')
sheet.write(0, 8, 'CPUTime')
workbook.save(filename) 

In [62]:
kf = KFold(n_splits=10)
kf.get_n_splits(X)
print(kf)
iter=0;
for train, test in kf.split(X):
    
    print("Fold:%d" % (iter))
    #print("%s %s" % (train, test))
    X_train=X[train]
    print(X_train.shape)
    y_train=y[train]
    X_test=X[test]
    y_test=y[test]
    #for i in range(y_test.shape[0]):
            #print(y_test[i])
    
    model = svm.SVC(kernel='rbf', gamma=0.5, C=1e+6)
    
    start_time = timeit.default_timer()
    model.fit(X_train, y_train)
    end_time = timeit.default_timer()
    exec_time=end_time-start_time
    #calculate training accuracy
    y_train_pred=model.predict(X_train)
    train_acc=training_accuracy(y_train, y_train_pred)
   
    print("Train Accuracy=%0.2f" % (train_acc))
    y_pred=model.predict(X_test)
    #for i in range(y_pred.shape[0]):
            #print(y_pred[i])
    conf_matrix=myConfusion_Matrix(y_test, y_pred)
    print(conf_matrix)
    acc, recall, spec, precision, F1, GM, FPR=classification_performance(conf_matrix)
    print("Accuracy: %0.2f, Recall=%0.2f, specificity=%0.2f, precision=%0.2f, F1=%0.2f, GM=%0.2f, FPR=%0.2f" % (acc, recall, spec, precision, F1, GM, FPR))
    iter=iter+1
    #writing to excel file
    sheet.write(iter, 0, acc) 
    sheet.write(iter, 1, recall) 
    sheet.write(iter, 2, spec) 
    sheet.write(iter, 3, precision) 
    sheet.write(iter, 4, F1) 
    sheet.write(iter, 5, GM) 
    sheet.write(iter, 6, FPR)
    sheet.write(iter, 7, train_acc)
    sheet.write(iter, 8, exec_time)
    workbook.save(filename) 
print("Classification using SVM is completed.")    

KFold(n_splits=10, random_state=None, shuffle=False)
Fold:0
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.98
[[15 10]
 [17 35]]
Accuracy: 0.65, Recall=0.47, specificity=0.78, precision=0.60, F1=0.53, GM=0.60, FPR=0.22
Fold:1
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[12 14]
 [10 41]]
Accuracy: 0.69, Recall=0.55, specificity=0.75, precision=0.46, F1=0.50, GM=0.64, FPR=0.25
Fold:2
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[16 14]
 [18 29]]
Accuracy: 0.58, Recall=0.47, specificity=0.67, precision=0.53, F1=0.50, GM=0.56, FPR=0.33
Fold:3
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[17 15]
 [13 32]]
Accuracy: 0.64, Recall=0.57, specificity=0.68, precision=0.53, F1=0.55, GM=0.62, FPR=0.32
Fold:4
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.96
[[12 12]
 [15 38]]
Accuracy: 0.65, Recall=0.44, specificity=0.76, precision=0.50, F1=0.47, GM=0.58, FPR=0.24
Fold:5
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[14  9]
 [16 38]]
Accuracy: 0.68, Recall=0.47, specificity=0.81, precision=0.61, F1=0.53, GM=0.61, FPR=0.19
Fold:6
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[ 8 16]
 [ 6 47]]
Accuracy: 0.71, Recall=0.57, specificity=0.75, precision=0.33, F1=0.42, GM=0.65, FPR=0.25
Fold:7
(691, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[15 13]
 [10 39]]
Accuracy: 0.70, Recall=0.60, specificity=0.75, precision=0.54, F1=0.57, GM=0.67, FPR=0.25
Fold:8
(692, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[15 13]
 [ 9 39]]
Accuracy: 0.71, Recall=0.62, specificity=0.75, precision=0.54, F1=0.58, GM=0.68, FPR=0.25
Fold:9
(692, 8)


G:\Anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy=0.97
[[15  9]
 [15 37]]
Accuracy: 0.68, Recall=0.50, specificity=0.80, precision=0.62, F1=0.56, GM=0.63, FPR=0.20
Classification using SVM is completed.
